export var global = {
  versao : "Free", // Free ou Pago
  dados: {
    "cabeca": {
      "disfuncao_miofascial_de_adutor_curto_longo_esquerdo": "disfunção miofascial de adutor curto longo esquerdo",
      "angioedema_de_face" : "angioedema de face",
      "enxaqueca_cold_patch_esquerdo" : "Enxaqueca - cold patch esquerdo",
      "insonia_congestao_periocular": "Insônia - congestao periocular",
      "cavidade_oral_dentes" : "cavidade oral - dentes",
      "enxaqueca_cold_patch_direito" : "Enxaqueca - cold patch direito", // Continuar daqui
      "enxaqueca_cold_patch_direito_inflamacao_neurogenica_direita" : "Enxaqueca - cold patch direito - inflamação neurogênica direita",
      "enxaqueca_cold_patch_esquerdo_inflamacao_neurogenica_direita" : "Enxaqueca - cold patch esquerdo - inflamação neurogênica direita",
      "Esclerite - episclerite" : "esclerite_episclerite",
      "Face oblíqua normal" : "face_obliqua_normal",
      "Disfunção temporomandibular (DTM) - Face direita" : "disfuncao_temporomandibular_DTM_face_direita",
      "Disfunção temporomandibular (DTM) - Face esquerda" : "disfuncao_temporomandibular_DTM_face_esquerda",
      "Fibroadenoma em mama esquerda - Pulpopatia de 1o pré-molar inferior esquerdo" : "fibroadenoma_em_mama_esquerda_pulpopatia_de_1o_pre_molar_inferior_esquerdo",
      "Neuralgia trigêmio direito" : "neuralgia_trigemio_direito",
      "Close-up de olho direito - filme lacrimal - normal" : "close_up_de_olho_direito_filme_lacrimal_normal",
      "Parotidite direita" : "parotidite_direita",
      "Prognatismo mandibular - disfunção miofascial de masseter esquerdo - disfunção temporomandibulat (DTM)" : "prognatismo_mandibular_disfuncao_miofascial_de_masseter_esquerdo_disfuncao_temporomandibulat_DTM",
      "Disfunção miofascial de pterigoideos direito" : "disfuncao_miofascial_de_pterigoideos_direito",
      "Disfunção miofascial de pterigoideos bilateral" : "disfuncao_miofascial_de_pterigoideos_bilateral",
      "Síndrome de ardência bucal" : "sindrome_de_ardencia_bucal",
      "Sinusite maxilar direita - sinusite frontal direita" : "sinusite_maxilar_direita_sinusite_frontal_direita",
      "Disfunção miofascial de subescapular direito - ponto-gatilho miofascial (PG)" : "disfuncao_miofascial_de_subescapular_direito_ponto_gatilho_miofascial_PG",
      "Disfunção miofascial de suboccipitais esquerdo - ponto-gatilho miofascial (PG)" : "disfuncao_miofascial_de_suboccipitais_esquerdo_ponto_gatilho_miofascial_PG",
      "Tumor esofagogástrico operado - metástase de linfonodos cervicais" : "tumor_esofagogastrico_operado_metastase_de_linfonodos_cervicais",
      "Termografia normal de face" : "termografia_normal_de_face",
      "Bócio mergulhante - congestão periocular - insônia" : "bocio_mergulhante_congestao_periocular_insonia",
      "Bócio mergulhante" : "bocio_mergulhante",
      "Congestao periocular - insônia" : "congestao_periocular_insonia",
      "Disfunção miofascial de esternocleidomastóideo" : "disfuncao_miofascial_de_esternocleidomastoideo",
      "Neuropatia de glossofaríngeo direito" : "neuropatia_de_glossofaringeo_direito",
      "Síndrome pós-herpética território trigeminal direito" : "sindrome_pos_herpetica_territorio_trigeminal_direito",
      "Insuficiência de carótica externa esquerda" : "insuficiencia_de_carotica_externa_esquerda",
      "Insuficiência de carótica interna direita - circulação colateral de temporal superficial direita" : "insuficiencia_de_carotica_interna_direita_circulacao_colateral_de_temporal_superficial_direita",
      "Neuralgia trigeminal direita" : "neuralgia_trigeminal_direita",
      "Olhos close-up - túnel de temperatura cerebral (BTT) - normal" : "olhos_close_up_tunel_de_temperatura_cerebral_BTT_normal",
      "sinusite maxilar esquerda - criança" : "sinusite_maxilar_esquerda_crianca",
      "Neuralgia do trigêmio direito" : "neuralgia_do_trigemio_direito"
    },
    "total": {
      "corpo total mulher anterior - escoliose" : "corpo_total_mulher_anterior_escoliose",
      "corpo total mulher posterior - escoliose" : "corpo_total_mulher_posterior_escoliose",
      "Família - corpo total anterior - normal" : "familia_corpo_total_anterior_normal",
      "Controle normal (linha superior) - Síndrome fibromiálgica (linha inferior) - fibromialgia" : "controle_normal_linha_superior_sindrome_fibromialgica_linha_inferior_fibromialgia",
      "Doença arterial oclusiva femoro-poplítea e tibial posterior direita (DAOP)" : "doenca_arterial_oclusiva_femoro_poplitea_e_tibial_posterior_direita_DAOP",
      "Espondilite anquilosante - Anquilose lombar - retificação lombar" : "espondilite_anquilosante_anquilose_lombar_retificacao_lombar",
      "Termografia de mama normal - referência térmica dos olhos - túnel de temperatura cerebral (BTT)" : "termografia_de_mama_normal_referencia_termica_dos_olhos_tunel_de_temperatura_cerebral_BTT",
      "Mielopatia - estenose lombar L4-L5 - padrão central" : "mielopatia_estenose_lombar_L4_L5_padrao_central",
      "Neuroma ulnar" : "neuroma_ulnar",
      "mulher obesa" : "mulher_obesa",
      "Síndrome facetária lombar - disfunção miofascial de glúteos direito - dor referida em membro inferior direito" : "sindrome_facetaria_lombar_disfuncao_miofascial_de_gluteos_direito_dor_referida_em_membro_inferior_direito",
      "síndrome complexa de dor regional de membro superior direito (SCDR)" : "sindrome_complexa_de_dor_regional_de_membro_superior_direito_SCDR"
    },
    "torax": {
      "disfunção esofagogastrica - doença do refluxo gastricoesofagico" : "disfuncao_esofagogastrica_doenca_do_refluxo_gastricoesofagico",
      "Dor cardíaca - angina" : "dor_cardiaca_angina",
      "osteoartrite veretebral - artrose de coluna - espondilite anquilosante" : "osteoartrite_veretebral_artrose_de_coluna_espondilite_anquilosante",
      "bursite subacromial subdeltoidea direita" : "bursite_subacromial_subdeltoidea_direita",
      "bursite subacromial direita - tendinopatia infra-espinhal direita" : "bursite_subacromial_direita_tendinopatia_infra_espinhal_direita",
      "envolvimento C6 bilateral - radiculopatia sensitiva" : "envolvimento_C6_bilateral_radiculopatia_sensitiva",
      "envolvimento C6 direita - radiculopatia sensitiva" : "envolvimento_C6_direita_radiculopatia_sensitiva",
      "envolvimento C5 esquerda - radiculopatia sensitiva" : "envolvimento_C5_esquerda_radiculopatia_sensitiva",
      "envolvimento C8 e T1 direita - radiculopatia sensitiva - atenção não é câncer de mama" : "envolvimento_C8_e_T1_direita_radiculopatia_sensitiva_atencao_nao_e_cancer_de_mama",
      "Câncer de esofago -metástase cervical - ponto MU dorsal" : "cancer_de_esofago_metastase_cervical_ponto_MU_dorsal",
      "Câncer de esofago -metástase cervical" : "cancer_de_esofago_metastase_cervical",
      "Câncer de mama direita - Carcinoma  lobular infiltrante" : "cancer_de_mama_direita_carcinoma_lobular_infiltrante",
      "Metástase cervical - câncer de mama direita - Carcinoma  lobular infiltrante" : "metastase_cervical_cancer_de_mama_direita_carcinoma_lobular_infiltrante",
      "Câncer de mama direita - Carcinoma ductal invasivo" : "cancer_de_mama_direita_carcinoma_ductal_invasivo",
      "Câncer de mama direita" : "cancer_de_mama_direita",
      "cefaléia de Arnold - cefaléia cervicogênica - neuropatia occipital" : "cefaleia_de_arnold_cefaleia_cervicogenica_neuropatia_occipital",
      "Cervicalgia em paciente com disfunção temporomandibular (DTM)" : "cervicalgia_em_paciente_com_disfuncao_temporomandibular_DTM",
      "Cervicalgia - disfunção miofascial de levantador da escápula direita" : "cervicalgia_disfuncao_miofascial_de_levantador_da_escapula_direita",
      "Colecistopatia" : "colecistopatia",
      "Colite" : "colite",
      "cefaléia cervicogênica" : "cefaleia_cervicogenica",
      "disfunção miofascial de levantador da escápula esquerda" : "disfuncao_miofascial_de_levantador_da_escapula_esquerda",
      "disfunção miofascial de levantador da escápula direita" : "disfuncao_miofascial_de_levantador_da_escapula_direita",
      "costocondrite - síndrome de Tietze" : "costocondrite_sindrome_de_tietze",
      "síndrome do desfiladeiro torácico bilateral" : "sindrome_do_desfiladeiro_toracico_bilateral",
      "Discopatia degenerativa cervical" : "discopatia_degenerativa_cervical",
      "Discopatia degenerativa lombar L4" : "discopatia_degenerativa_lombar_L4",
      "Discopatia degenerativa lombar L5" : "discopatia_degenerativa_lombar_L5",
      "Discopatia degenerativa lombar S1" : "discopatia_degenerativa_lombar_S1",
      "Discopatia degenerativa lombar S1 - disco negro na RM" : "discopatia_degenerativa_lombar_S1_disco_negro_na_RM",
      "Discopatia degenerativa lombar S1 - sacroileíte esquerda" : "discopatia_degenerativa_lombar_S1_sacroileite_esquerda",
      "Disfunção intestinal - lesao medular" : "disfuncao_intestinal_lesao_medular",
      "Disfunção intestinal" : "disfuncao_intestinal",
      "Disfunção sacroilíaca esquerda" : "disfuncao_sacroiliaca_esquerda",
      "Disfunção supra-espinal direita" : "disfuncao_supra_espinal_direita",
      "Discopatia degenerativa lombar L3 e L5 - dor discogênica" : "discopatia_degenerativa_lombar_L3_e_L5_dor_discogenica",
      "Endometriose" : "endometriose",
      "disfunção miofascial de esplênio da cabeça esquerda" : "disfuncao_miofascial_de_esplenio_da_cabeca_esquerda",
      "Espondilodiscoartropatia - discopatia degenerativa lombar" : "espondilodiscoartropatia_discopatia_degenerativa_lombar",
      "Disfunção miofascial de esternocleidomastoideo bilateral - dor esternal" : "disfuncao_miofascial_de_esternocleidomastoideo_bilateral_dor_esternal",
      "Disfunção miofascial de esternocleidomastoideo esquerdo" : "disfuncao_miofascial_de_esternocleidomastoideo_esquerdo",
      "Disfunção miofascial de esternocleidomastoideo bilateral - hipermobilidade" : "disfuncao_miofascial_de_esternocleidomastoideo_bilateral_hipermobilidade",
      "Artrose facetária cervical - síndrome facetária - osteoartropatia facetária" : "artrose_facetaria_cervical_sindrome_facetaria_osteoartropatia_facetaria",
      "Artrose facetária lombar - síndrome facetária - osteoartropatia facetária - discopatia degenerativa lombar" : "artrose_facetaria_lombar_sindrome_facetaria_osteoartropatia_facetaria_discopatia_degenerativa_lombar",
      "Artrose facetária lombar - síndrome facetária - osteoartropatia facetária L4-L5 direita" : "artrose_facetaria_lombar_sindrome_facetaria_osteoartropatia_facetaria_L4_L5_direita",
      "Artrose facetária lombar - síndrome facetária - osteoartropatia facetária L5-S1 - disfunção miofascial de quadrado lombar esquerdo" : "artrose_facetaria_lombar_sindrome_facetaria_osteoartropatia_facetaria_L5_S1_disfuncao_miofascial_de_quadrado_lombar_esquerdo",
      "Artrose facetária lombar - síndrome facetária - osteoartropatia facetária L4-L5 e L5-S1" : "artrose_facetaria_lombar_sindrome_facetaria_osteoartropatia_facetaria_L4_L5_e_L5_S1",
      "Disfunção hepática - hepatopatia" : "disfuncao_hepatica_hepatopatia",
      "Gastrite - gastropatia" : "gastrite_gastropatia",
      "lesão em golpe de sabre - esclerodermia linear - pós lipoaspiração" : "lesao_em_golpe_de_sabre_esclerodermia_linear_pos_lipoaspiracao",
      "Disfunção miofascial de íliopsoas esquerdo" : "disfuncao_miofascial_de_iliopsoas_esquerdo",
      "Tendinopatia infra-espinal esquerda" : "tendinopatia_infra_espinal_esquerda",
      "Disfunção miofascial infra-espinal bilateral" : "disfuncao_miofascial_infra_espinal_bilateral",
      "Disfunção miofascial de levantador da escápula direita e trapézio esquerdo" : "disfuncao_miofascial_de_levantador_da_escapula_direita_e_trapezio_esquerdo",
      "Síndrome fibromiálgica - sinal do manto com detalhe de aperfeiçoamento digital (DDE) - fibromialgia" : "sindrome_fibromialgica_sinal_do_manto_com_detalhe_de_aperfeiçoamento_digital_DDE_fibromialgia",
      "Mastectomia direita - modo mistura" : "mastectomia_direita_modo_mistura",
      "Metástase hepática - fígado" : "metastase_hepatica_figado",
      "Meralgia parestésia de coxa esquerda - neuropatia de cutâneo femoral lateral" : "meralgia_parestesia_de_coxa_esquerda_neuropatia_de_cutaneo_femoral_lateral",
      "Neurofibromatose direita -  Doença de Von Recklinghausen" : "neurofibromatose_direita_doenca_de_von_recklinghausen",
      "Osteoartrite de ombro direito - osteoartrite acrômioclavicular - artrose" : "osteoartrite_de_ombro_direito_osteoartrite_acromioclavicular_artrose",
      "Capsulite adesiva - ombro congelado direito - dor de manutenção simpática -síndrome complexa de dor regional (SCDR)" : "capsulite_adesiva_ombro_congelado_direito_dor_de_manutencao_simpatica_sindrome_complexa_de_dor_regional_SCDR",
      "Pancreatite" : "pancreatite",
      "Disfunção miofascial de romboide direito" : "disfuncao_miofascial_de_romboide_direito",
      "Disfunção miofascial de romboide esquerdo" : "disfuncao_miofascial_de_romboide_esquerdo",
      "Síndrome esternal" : "sindrome_esternal",
      "Disfunção miofascial de serrátil anterior direito" : "disfuncao_miofascial_de_serratil_anterior_direito",
      "Disfunção miofascial de serrátil posterior e grande dorsal direito" : "disfuncao_miofascial_de_serratil_posterior_e_grande_dorsal_direito",
      "Sofrimento cardíaco - angina" : "sofrimento_cardiaco_angina",
      "Tendinopatia supra-espinal bilateral" : "tendinopatia_supra_espinal_bilateral",
      "Tendinopatia supra-espinal direito" : "tendinopatia_supra_espinal_direito",
      "Tendinopatia bicipital supra-espinal direita" : "tendinopatia_bicipital_supra_espinal_direita",
      "Tendinopatia de infra-espinal direito - sinal do til" : "tendinopatia_de_infra_espinal_direito_sinal_do_til",
      "Tendinopatia supra-espinal bilateral - obeso" : "tendinopatia_supra_espinal_bilateral_obeso",
      "Tendinopatia supra-espinal esquerda" : "tendinopatia_supra_espinal_esquerda",
      "Tendinopatia supra-espinal - disfunção miofascial supra-espinal direita" : "tendinopatia_supra_espinal_disfuncao_miofascial_supra_espinal_direita",
      "Tendinopatia supra-espinal direita" : "tendinopatia_supra_espinal_direita",
      "Tendinopatia supra-espinal bilateral - bursite subacromial e subdeltoidea esquerda" : "tendinopatia_supra_espinal_bilateral_bursite_subacromial_e_subdeltoidea_esquerda",
      "Tendinopatia supra-espinal direita aguda" : "tendinopatia_supra_espinal_direita_aguda",
      "Tendinopatia subescapular direita" : "tendinopatia_subescapular_direita",
      "Tendinopatia supra-espinal direita - sinal do gancho" : "tendinopatia_supra_espinal_direita_sinal_do_gancho",
      "disfunção tireoideana - tireóide anormal" : "disfuncao_tireoideana_tireoide_anormal",
      "Disfunção miofascial de trapézio superior bilateral" : "disfuncao_miofascial_de_trapezio_superior_bilateral",
      "Disfunção miofascial de trapézio inferior esquerdo" : "disfuncao_miofascial_de_trapezio_inferior_esquerdo",
      "Disfunção miofascial de tríceps braquial direito" : "disfuncao_miofascial_de_triceps_braquial_direito",
      "Tumor esofagogástrico operado" : "tumor_esofagogastrico_operado",
      "Tumor avançado de mama direita" : "tumor_avancado_de_mama_direita",
      "Tumor de mama esquerda - retração de mamilo (hiper-radiação)" : "tumor_de_mama_esquerda_retracao_de_mamilo_hiper_radiacao",
      "Exemplo de tumores malignos de mama - exceto caso 2 (superior direito) normal com mamas com hipervascularização moderada" : "exemplo_de_tumores_malignos_de_mama_exceto_caso_2_superior_direito_normal_com_mamas_com_hipervascularizacao_moderada",
      "Tumor de meninge - padrão térmico central - dor central" : "tumor_de_meninge_padrao_termico_central_dor_central",
      "Tumor de paratireoide esquerda" : "tumor_de_paratireoide_esquerda",
      "Tumor hepático maligno - fígado" : "tumor_hepatico_maligno_figado",
      "Prótese de  mamas - mamoplastia" : "protese_de_mamas_mamoplastia",
      "capsulite adesiva - ombro congelado direito - dor de manutenção simpática -síndrome complexa de dor regional (SCDR)- dor referida ombro" : "capsulite_adesiva_ombro_congelado_direito_dor_de_manutencao_simpática_sindrome_complexa_de_dor_regional_SCDR_dor_referida_ombro",
      "Entesopatia abdominal - disfunção miofascial de reto abdominal - pubalgia - ponto-gatilho miofascial (PG)" : "entesopatia_abdominal_disfuncao_miofascial_de_reto_abdominal_pubalgia_ponto_gatilho_miofascial_PG",
      "Osteoartrite acromioclavicular bilateral - artrose ombros" : "osteoartrite_acromioclavicular_bilateral_artrose_ombros",
      "Ingurgitamento venoso hormonal - Vascularização moderada  de mamas" : "ingurgitamento_venoso_hormonal_vascularizacao_moderada_de_mamas",
      "Avaliação do risco de deiscência abdominal - cicatriz cirúrgica - normal" : "avaliacao_do_risco_de_deiscencia_abdominal_cicatriz_cirurgica_normal",
      "Eletroacupuntura - síndrome pós-laminectomia lombar" : "eletroacupuntura_sindrome_pos_laminectomia_lombar",
      "tumor maligno de mama direita" : "tumor_maligno_de_mama_direita",
      "Termografia cervical anterior normal" : "termografia_cervical_anterior_normal",
      "Termografia de mama normal - padrão avascular grau 1" : "termografia_de_mama_normal_padrao_avascular_grau_1",
      "Síndrome pós-laminectomia - artrodese lombar - fixação com parafusos" : "sindrome_pos_laminectomia_artrodese_lombar_fixacao_com_parafusos",
      "Tumor maligno avançado de mama esquerda" : "tumor_maligno_avancado_de_mama_esquerda",
      "Tumor maligno avançado de mama direita" : "tumor_maligno_avançado_de_mama_direita",
      "Tumor maligno de mama direita - composição" : "tumor_maligno_de_mama_direita_composicao",
      "metástases supraclavicular direita" : "metastases_supraclavicular_direita",
      "Tumor maligno de mama direita grau 4 - cold stress test positivo" : "tumor_maligno_de_mama_direita_grau_4_cold_stress_test_positivo",
      "Câncer de mama direita avançado" : "cancer_de_mama_direita_avancado",
      "Doença de Graves - tireóide" : "doenca_de_graves_tireoide",
      "Doenca inflamatória intestinal (DII)" : "doenca_inflamatoria_intestinal_DII",
      "Osteoartropatia do cóccix - coccigodinia" : "osteoartropatia_do_coccix_coccigodinia",
      "Estenose de canal L4-L5 - lombalgia" : "estenose_de_canal_L4_L5_lombalgia",
      "Fibroadenoma de mama direita" : "fibroadenoma_de_mama_direita",
      "Hepatite" : "hepatite",
      "Hepatite viral" : "hepatite_viral",
      "Hérnia umbilical" : "hernia_umbilical",
      "Hiperplasia prostática benigna (HPB)" : "hiperplasia_prostatica_benigna_HPB",
      "Disfunção intestinal - Intolerância à glúten" : "disfuncao_intestinal_intolerancia_a_gluten",
      "Linfonodomegalia cervical esquerda - criança" : "linfonodomegalia_cervical_esquerda_crianca",
      "Neuralgia pós-herpética toracolombar esquerda" : "neuralgia_pos_herpetica_toracolombar_esquerda",
      "Disfunção miofascial de esternocleidomastoideo direito" : "disfuncao_miofascial_de_esternocleidomastoideo_direito",
      "Disfunção miofascial de redondo menor esquerdo" : "disfuncao_miofascial_de_redondo_menor_esquerdo",
      "Síndrome fibromiálgica - fibromialgia - sinal do manto - escala de contorno" : "sindrome_fibromialgica_fibromialgia_sinal_do_manto_escala_de_contorno",
      "Síndrome fibromiálgica - fibromialgia - sinal do manto" : "sindrome_fibromialgica_fibromialgia_sinal_do_manto",
      "Envolvimento de território C7 esquerdo - radiculopatia sensitiva" : "envolvimento_de_territorio_C7_esquerdo_radiculopatia_sensitiva"
    },
    "pelve" : {
      "bursite trocantérica bilateral" : "bursite_trocanterica_bilateral",
      "Cistite intersticial" : "cistite_intersticial",
      "Lombalgia - cistos perineurais - cistos de Tarlov" : "lombalgia_cistos_perineurais_cistos_de_tarlov",
      "Entesite trocantérica esquerda" : "entesite_trocanterica_esquerda",
      "Entesite trocanterica - pós-tratamento" : "entesite_trocanterica_pos_tratamento",
      "Entesite trocantérica - pré-tratamento" : "entesite_trocanterica_pre_tratamento",
      "Entesite trocantérica" : "entesite_trocanterica",
      "Sacroileíte - Espondilite anquilosante" : "sacroileite_espondilite_anquilosante",
      "Artrose facetária lombar - síndrome facetária - osteoartropatia facetária L5-S1 bilateral" : "artrose_facetaria_lombar_sindrome_facetaria_osteoartropatia_facetaria_L5_S1_bilateral",
      "Disfunção miofascial de glúteo médio bilateral" : "disfuncao_miofascial_de_gluteo_medio_bilateral",
      "Disfunção miofascial de glúteo mínimo direito" : "disfuncao_miofascial_de_gluteo_minimo_direito",
      "Disfunção miofascial de glúteo mínimo bilateral" : "disfuncao_miofascial_de_gluteo_minimo_bilateral",
      "Hérnia inguinal direita" : "hernia_inguinal_direita",
      "Envolvimento de território L5 direito - radiculopatia sensitiva" : "envolvimento_de_territorio_L5_direito_radiculopatia_sensitiva",
      "Radiculite L5 esquerda - radiculopatia sensitiva" : "radiculite_L5_esquerda_radiculopatia_sensitiva",
      "Disfunção sacroilíaca - discopatia degenerativa L5" : "disfuncao_sacroiliaca_discopatia_degenerativa_L5",
      "Neuralgia de pudendo direito" : "neuralgia_de_pudendo_direito",
      "Nódulo de tireóide maligno grau 4" : "nodulo_de_tireoide_maligno_grau_4",
      "Nódulo de tireóide em lobo esquerdo" : "nodulo_de_tireoide_em_lobo_esquerdo",
      "Nódulo de tireóide" : "nodulo_de_tireoide",
      "Osteíte condensante do ilíaco mais à esquerda - iliíte condensante" : "osteite_condensante_do_iliaco_mais_a_esquerda_iliite_condensante",
      "Disfunção miofascial de piriforme esquerdo - ponto-gatilho miofascial (PG)" : "disfuncao_miofascial_de_piriforme_esquerdo_ponto_gatilho_miofascial_PG",
      "Disfunção miofascial de piriforme esquerdo - ponto-gatilho miofascial (PG) - síndrome do piriforme" : "disfuncao_miofascial_de_piriforme_esquerdo_ponto_gatilho_miofascial_PG_sindrome_do_piriforme",
      "Disfunção miofascial de piriforme direito - ponto-gatilho miofascial (PG)" : "disfuncao_miofascial_de_piriforme_direito_ponto_gatilho_miofascial_PG",
      "Sìndrome pós-laminectomia - osteoartropatia facetária esquerda L3-L4 - Síndrome facetária" : "sindrome_pos_laminectomia_osteoartropatia_facetaria_esquerda_L3_L4_sindrome_facetaria",
      "Disfunção miofascial de quadrado lombar esquerdo" : "disfuncao_miofascial_de_quadrado_lombar_esquerdo",
      "Envolvimento de território L4 direito - radiculopatia sensitiva motora - atrofia de glúteo direito" : "envolvimento_de_territorio_L4_direito_radiculopatia_sensitiva_motora_atrofia_de_gluteo_direito",
      "Radiculite L5 direita - radiculopatia sensitiva" : "radiculite_L5_direita_radiculopatia_sensitiva",
      "Discopatia degenerativa S1 - dor discogênica" : "discopatia_degenerativa_S1_dor_discogenica",
      "Discopatia degenerativa S1 - dor discogênica - dor referida em território S1" : "discopatia_degenerativa_S1_dor_discogenica_dor_referida_em_territorio_S1",
      "Sacroileíte bilateral - osteoartrite facetária lombar - síndrome facetária lombar" : "sacroileite_bilateral_osteoartrite_facetaria_lombar_sindrome_facetária_lombar",
      "Sacroileíte bilateral" : "sacroileite_bilateral",
      "Sacroileíte direita" : "sacroileite_direita",
      "Sacroileíte direita - pré-tratamento" : "sacroileite_direita_pre_tratamento",
      "Sacroileíte direita - pós-tratamento" : "sacroileite_direita_pos_tratamento",
      "Sacroileíte esquerda" : "sacroileite_esquerda",
      "Sacroileíte esquerda - síndrome pós-laminectomia" : "sacroileite_esquerda_sindrome_pos_laminectomia",
      "Sobrecarga trocantérica esquerda - tensão mecânica" : "sobrecarga_trocanterica_esquerda_tensao_mecanica",
      "Disfunção miofascial de tensor da fáscia lata bilateral" : "disfuncao_miofascial_de_tensor_da_fascia_lata_bilateral",
      "Disfunção miofascial de tensor da fáscia lata direita" : "disfuncao_miofascial_de_tensor_da_fascia_lata_direita",
      "Sacroileite - artrite psoriática" : "sacroileite_artrite_psoriatica"
    },
    "membros_inferiores": {
      "tendinopatia de Aquiles (calcâneo) esquerdo" : "tendinopatia_de_aquiles_calcaneo_esquerdo",
      "polineuropatia simétrica distal - diabetes - pé diabético" : "polineuropatia_simetrica_distal_diabetes_pe_diabetico",
      "polineuropatia simétrica distal - diabetes - pé diabético - amputação - inflamação - cicatrização de ferida" : "polineuropatia_simetrica_distal_diabetes_pe_diabetico_amputacao_inflamacao_cicatrizacao_de_ferida",
      "disfunção miofascial de bíceps femoral esquerdo" : "disfuncao_miofascial_de_biceps_femoral_esquerdo",
      "síndrome complexa de dor regional - SCDR - pé plantar direita - cold stress test positivo" : "sindrome_complexa_de_dor_regional_SCDR_pe_plantar_direita_cold_stress_test_positivo",
      "envolvimento L5 direito - radiculopatia sensitiva - cold stress test positivo" : "envolvimento_L5_direito_radiculopatia_sensitiva_cold_stress_test_positivo",
      "envolvimento L5 e S1 direito - radiculopatia sensitiva - cold stress test positivo" : "envolvimento_L5_e_S1_direito_radiculopatia_sensitiva_cold_stress_test_positivo",
      "Condromalácia" : "condromalacia",
      "Condromalácia grau 4 joelho esquerdo" : "condromalacia_grau_4_joelho_esquerdo",
      "Condromalácia - tendinopatia patelar" : "condromalacia_tendinopatia_patelar",
      "Distensão isquiotibiais esquerdo - estiramento - lesão" : "distensao_isquiotibiais_esquerdo_estiramento_lesao",
      "Entorse de tornozelo em inversão" : "entorse_de_tornozelo_em_inversao",
      "Entorse de  tornozelo esquerdo" : "entorse_de_tornozelo_esquerdo",
      "Estiramento de ligamento colateral medial do joelho esquerdo - lesão - distensão" : "estiramento_de_ligamento_colateral_medial_do_joelho_esquerdo_lesao_distensao",
      "Disfunção miofascial de gastrocnêmio medial esquerdo" : "disfuncao_miofascial_de_gastrocnemio_medial_esquerdo",
      "Varizes - estase venosa" : "varizes_estase_venosa",
      "Disfunção miofascial de grácil direito" : "disfuncao_miofascial_de_gracil_direito",
      "Osteoartrite de joelhos - artrose - Imagem cedida gentilmente pelo Dr Haroldo Barbosa" : "osteoartrite_de_joelhos_artrose_imagem_cedida_gentilmente_pelo_dr_haroldo_barbosa",
      "Lesão de ligamento colateral anterior (LCA) e menisco medial de joelho direito" : "lesao_de_ligamento_colateral_anterior_LCA_e_menisco_medial_de_joelho_direito",
      "Lesão de ligamento patelar direito" : "lesao_de_ligamento_patelar_direito",
      "Lesão menisco medial direito" : "lesao_menisco_medial_direito",
      "Lesão menisco medial esquerdo" : "lesao_menisco_medial_esquerdo",
      "Lesão muscular de gastrocnêmios esquerdo - edema muscular" : "lesao_muscular_de_gastrocnemios_esquerdo_edema_muscular",
      "Lesão de menisco medial esquerdo" : "lesao_de_menisco_medial_esquerdo",
      "Neuroma de amputação em coxa direita" : "neuroma_de_amputacao_em_coxa_direita",
      "Neuropatia compressiva do nervo digital - Neuroma de Morton - cold stress test positivo" : "neuropatia_compressiva_do_nervo_digital_neuroma_de_morton_cold_stress_test_positivo",
      "Neuroma de Morton bilateralmente" : "neuroma_de_morton_bilateralmente",
      "Neuropatia compressiva do nervo digital - Neuroma de Morton" : "neuropatia_compressiva_do_nervo_digital_neuroma_de_morton",
      "Neuropatia fibular superficial esquerda" : "neuropatia_fibular_superficial_esquerda",
      "Osteoartrite de joelho direito (artrose) - joelho esquerdo normal" : "osteoartrite_de_joelho_direito_artrose_joelho_esquerdo_normal",
      "Osteoartrite joelhos (artrose)" : "osteoartrite_joelhos_artrose",
      "Panaricio de hálux direito - Erisipela de perna direita" : "panaricio_de_halux_direito_erisipela_de_perna_direita",
      "Tendinopatia anserina - tendinite da pata de ganso esquerda" : "tendinopatia_anserina_tendinite_da_pata_de_ganso_esquerda",
      "Pés cavos - doença de Charcot-Marrie-Tooth" : "pes_cavos_doenca_de_charcot_marrie_tooth",
      "Próteses de joelhos - bom resultado" : "proteses_de_joelhos_bom_resultado",
      "Fenômeno de Raynaud em pés" : "fenomeno_de_raynaud_em_pes",
      "Envolvimento de território S1 direito - radiculopatia sensitiva" : "envolvimento_de_territorio_S1_direito_radiculopatia_sensitiva",
      "Tendinopatia anserina - tendinite da pata de ganso direita" : "tendinopatia_anserina_tendinite_da_pata_de_ganso_direita",
      "Tendinopatia de Aquiles (calcâneo) esquerdo" : "tendinopatia_de_aquiles_calcaneo_esquerdo",
      "tendinopatia de Aquiles (calcâneo) bilateral" : "tendinopatia_de_aquiles_calcaneo_bilateral",
      "tendinopatia de Aquiles (calcâneo) direito" : "tendinopatia_de_aquiles_calcaneo_direito",
      "Tendinopatia de  extensores de pe esquerdo" : "tendinopatia_de_extensores_de_pe_esquerdo",
      "Tendinopatia do quadríceps fermoral direito" : "tendinopatia_do_quadriceps_fermoral_direito",
      "Tendinopatia patelar esquerda" : "tendinopatia_patelar_esquerda",
      "Tendinopatia do quadríceps fermoral esquerda" : "tendinopatia_do_quadriceps_fermoral_esquerda",
      "Tendinopatia tibial posterior bilateral" : "tendinopatia_tibial_posterior_bilateral",
      "Úlcera isquêmica em antepé direito" : "ulcera_isquemica_em_antepe_direito",
      "Varizes - estase venosa - modo fusão" : "varizes_estase_venosa_modo_fusao",
      "Varizes - estase venosa - perfurantes insuficientes (vermelho)" : "varizes_estase_venosa_perfurantes_insuficientes_vermelho",
      "Varizes - veia de Giacomini - estase venosa" : "varizes_veia_de_giacomini_estase_venosa",
      "doença arterial obstrutiva periférica (DAOP) - insuficiência arterial de membros inferiores" : "doenca_arterial_obstrutiva_periferica_DAOP_insuficiencia_arterial_de_membros_inferiores",
      "Termografia plantar normal" : "termografia_plantar_normal",
      "Úlceras isquêmicas plantares" : "ulceras_isquemicas_plantares",
      "Artrite reumatóide juvenil em joelhos" : "artrite_reumatoide_juvenil_em_joelhos",
      "Artrite reumatóide em tornozelos posterior" : "artrite_reumatoide_em_tornozelos_posterior",
      "Osteoartrite de joelhos - artrose de joelhos" : "osteoartrite_de_joelhos_artrose_de_joelhos",
      "Condromalácia de joelhos - disfunção patelar" : "condromalacia_de_joelhos_disfuncao_patelar",
      "Gota de hálux esquerdo - artrite cristalina" : "gota_de_halux_esquerdo_artrite_cristalina",
      "Disfunção miofascial de íliopsoas direito" : "disfuncao_miofascial_de_iliopsoas_direito",
      "Distensão isquiotibiais direito - estiramento - lesão" : "distensao_isquiotibiais_direito_estiramento_lesao",
      "Estiramento de ligamento colateral lateral do joelho esquerdo - lesão - distensão" : "estiramento_de_ligamento_colateral_lateral_do_joelho_esquerdo_lesao_distensao",
      "Polineuropatia simétrica distal - diabetes - pé diabético - áreas de risco de ulceração" : "polineuropatia_simetrica_distal_diabetes_pe_diabetico_areas_de_risco_de_ulceracao",
      "Varizes - Síndrome pós-flebítica - estase venosa" : "varizes_sindrome_pos_flebitica_estase_venosa"
    },
    "membros_superiores": {
      "artrite de mãos e punhos" : "artrite_de_maos_e_punhos",
      "artrite de mãos" : "artrite_de_maos",
      "osteoartrite de mãos (artrose)" : "osteoartrite_de_maos_artrose",
      "osteoartrite de mãos (artrose) - radiculopatia C6 C7 bilateral" : "osteoartrite_de_maos_artrose_radiculopatia_C6_C7_bilateral_cold_stress_positivo",
      "síndrome complexa de dor regional - SCDR - causalgia de mão direita" : "sindrome_complexa_de_dor_regional_SCDR_causalgia_de_mao_direita",
      "síndrome complexa de dor regional - SCDR - mão direita - cold stress test positivo" : "sindrome_complexa_de_dor_regional_SCDR_mao_direita_cold_stress_test_positivo",
      "Epicondilite lateral bilateral" : "epicondilite_lateral_bilateral",
      "Epicondilite lateral direita" : "epicondilite_lateral_direita",
      "Epicondilite lateral direita - bursite subacromail subdeltoidea direita" : "epicondilite_lateral_direita_bursite_subacromail_subdeltoidea_direita",
      "Epicondilite lateral direita - tendinopatia supra-espinal direita" : "epicondilite_lateral_direita_tendinopatia_supra_espinal_direita",
      "Osteoartrite de mãos - rizoartrose - artrose" : "osteoartrite_de_maos_rizoartrose_artrose",
      "Síndrome do túnel do carpo (STC) direito - neuropatia de mediano - fratura de amato (punho) direito" : "sindrome_do_tunel_do_carpo_STC_direito_neuropatia_de_mediano_fratura_de_amato_punho_direito",
      "Síndrome do túnel do carpo (STC) - síndrome complexa de dor regional (SCDR) - imobilizacao pós-fratura" : "sindrome_do_tunel_do_carpo_STC_sindrome_complexa_de_dor_regional_SCDR_imobilizacao_pos_fratura",
      "Síndrome do túnel do carpo (STC) - neuropatia mediano direito" : "sindrome_do_tunel_do_carpo_STC_neuropatia_mediano_direito",
      "Tendinopatia de flexores de punho esquerdo" : "tendinopatia_de_flexores_de_punho_esquerdo",
      "Tenossinovite de extensores do punho" : "tenossinovite_de_extensores_do_punho",
      "Isquemia digital - limite de amputação - viabilidade da microcirculação" : "isquemia_digital_limite_de_amputacao_viabilidade_da_microcirculacao",
      "isquemia digital pós fratura e recontrução" : "isquemia_digital_pos_fratura_e_recontrucao",
      "viabilidade do risco de isquemia digital pós fratura e recontrução" : "viabilidade_do_risco_de_isquemia_digital_pos_fratura_e_recontrucao",
      "Envolvimento de território C6 esquerdo - radiculopatia sensitiva" : "envolvimento_de_territorio_C6_esquerdo_radiculopatia_sensitiva",
      "Envolvimento de território C6 esquerda - radiculopatia sensitiva - tendinopatia bicipital direita" : "envolvimento_de_territorio_C6_esquerda_radiculopatia_sensitiva_tendinopatia_bicipital_direita",
      "Teste de disfunção endotelial - braquial test - boa resposta - baixo risco cardiovascular" : "teste_de_disfuncao_endotelial_braquial_test_boa_resposta_baixo_risco_cardiovascular",
      "Gradiente térmico distal normal das mãos - padrão em casca de cebola - degrade normal" : "gradiente_termico_distal_normal_das_maos_padrao_em_casca_de_cebola_degrade_normal",
      "Quebra do gradiente térmico distal das mãos - padrão anárquico -anormal" : "quebra_do_gradiente_termico_distal_das_maos_padrao_anarquico_anormal",
      "Veias superficiais do dorso da mão" : "veias_superficiais_do_dorso_da_mao",
      "osteoartrite de mãos e punhos (artrose)" : "osteoartrite_de_maos_e_punhos_artrose",
      "Plexopatia direita - Síndrome de Parsonage-Turner" : "plexopatia_direita_sindrome_de_parsonage_turner",
      "Fenômeno de Raynaud" : "fenomeno_de_raynaud"
    }
  },

  imgs: {
    "artrite_de_maos_e_punhos" : 7,
    "artrose_facetaria_cervical_sindrome_facetaria_osteoartropatia_facetaria" : 2,
    "artrose_facetaria_lombar_sindrome_facetaria_osteoartropatia_facetaria_L5_S1_disfuncao_miofascial_de_quadrado_lombar_esquerdo" : 2,
    "avaliacao_do_risco_de_deiscencia_abdominal_cicatriz_cirurgica_normal" : 2,
    "cancer_de_esofago_metastase_cervical" : 3,
    "cancer_de_mama_direita_avancado" : 3,
    "cancer_de_mama_direita_carcinoma_lobular_infiltrante" : 2,
    "cavidade_oral_dentes" : 3,
    "cefaleia_de_arnold_cefaleia_cervicogenica_neuropatia_occipital" : 2,
    "condromalacia" : 2,
    "condromalacia_de_joelhos_disfuncao_patelar" : 2,
    "corpo_total_mulher_anterior_escoliose" : 5,
    "discopatia_degenerativa_cervical" : 3,
    "discopatia_degenerativa_lombar_L4" : 2,
    "discopatia_degenerativa_lombar_L5" : 8,
    "discopatia_degenerativa_lombar_S1" : 2,
    "discopatia_degenerativa_lombar_S1_disco_negro_na_RM" : 2,
    "disfuncao_intestinal_intolerancia_a_gluten" : 2,
    "disfuncao_miofascial_de_adutor_curto_longo_esquerdo" : 2,
    "disfuncao_miofascial_de_biceps_femoral_esquerdo" : 2,
    "disfuncao_miofascial_de_esternocleidomastoideo_bilateral_dor_esternal" : 2,
    "disfuncao_miofascial_de_esternocleidomastoideo_esquerdo" : 2,
    "disfuncao_miofascial_de_gluteo_minimo_direito" : 3,
    "disfuncao_miofascial_de_piriforme_esquerdo_ponto_gatilho_miofascial_PG" : 3,
    "disfuncao_miofascial_de_piriforme_esquerdo_ponto_gatilho_miofascial_PG_sindrome_do_piriforme" : 2,
    "disfuncao_miofascial_de_pterigoideos_direito" : 2,
    "disfuncao_miofascial_de_redondo_menor_esquerdo" : 2,
    "disfuncao_miofascial_de_serratil_posterior_e_grande_dorsal_direito" : 3,
    "disfuncao_miofascial_de_subescapular_direito_ponto_gatilho_miofascial_PG" : 2,
    "disfuncao_supra_espinal_direita" : 2,
    "disfuncao_tireoideana_tireoide_anormal" : 6,
    "distensao_isquiotibiais_esquerdo_estiramento_lesao" : 2,
    "endometriose" : 3,
    "entesopatia_abdominal_disfuncao_miofascial_de_reto_abdominal_pubalgia_ponto_gatilho_miofascial_PG" : 2,
    "envolvimento_C6_bilateral_radiculopatia_sensitiva" : 2,
    "envolvimento_C6_direita_radiculopatia_sensitiva" : 2,
    "envolvimento_de_territorio_C6_esquerdo_radiculopatia_sensitiva" : 3,
    "envolvimento_de_territorio_S1_direito_radiculopatia_sensitiva" : 3,
    "enxaqueca_cold_patch_direito" : 3,
    "enxaqueca_cold_patch_esquerdo" : 5,
    "epicondilite_lateral_direita" : 2,
    "face_obliqua_normal" : 2,
    "fenomeno_de_raynaud_em_pes" : 3,
    "fibroadenoma_de_mama_direita" : 3,
    "gastrite_gastropatia" : 2,
    "gota_de_halux_esquerdo_artrite_cristalina" : 2,
    "hepatite_viral" : 2,
    "hernia_inguinal_direita" : 2,
    "hernia_umbilical" : 2,
    "insuficiencia_de_carotica_externa_esquerda" : 3,
    "isquemia_digital_limite_de_amputacao_viabilidade_da_microcirculacao" : 4,
    "lesao_de_ligamento_colateral_anterior_LCA_e_menisco_medial_de_joelho_direito" : 3,
    "linfonodomegalia_cervical_esquerda_crianca" : 4,
    "lombalgia_cistos_perineurais_cistos_de_tarlov" : 2,
    "metastase_hepatica_figado" : 3,
    "mielopatia_estenose_lombar_L4_L5_padrao_central" : 4,
    "mulher_obesa" : 2,
    "neuralgia_pos_herpetica_toracolombar_esquerda" : 4,
    "neuralgia_trigeminal_direita" : 3,
    "neuralgia_trigemio_direito" : 3,
    "neurofibromatose_direita_doenca_de_von_recklinghausen" : 3,
    "neuroma_de_amputacao_em_coxa_direita" : 4,
    "neuropatia_fibular_superficial_esquerda" : 4,
    "nodulo_de_tireoide_em_lobo_esquerdo" : 2,
    "osteite_condensante_do_iliaco_mais_a_esquerda_iliite_condensante" : 2,
    "osteoartrite_acromioclavicular_bilateral_artrose_ombros" : 6,
    "osteoartrite_de_maos_artrose" : 7,
    "osteoartrite_joelhos_artrose" : 3,
    "plexopatia_direita_sindrome_de_parsonage_turner" : 3,
    "polineuropatia_simetrica_distal_diabetes_pe_diabetico_amputacao_inflamacao_cicatrizacao_de_ferida" : 5,
    "polineuropatia_simetrica_distal_diabetes_pe_diabetico" : 14,
    "sacroileite_bilateral" : 3,
    "sacroileite_bilateral_osteoartrite_facetaria_lombar_sindrome_facetária_lombar" : 2,
    "sindrome_complexa_de_dor_regional_de_membro_superior_direito_SCDR" : 2,
    "sindrome_de_ardencia_bucal" : 3,
    "sindrome_do_desfiladeiro_toracico_bilateral" : 2,
    "sindrome_fibromialgica_fibromialgia_sinal_do_manto" : 2,
    "sindrome_fibromialgica_fibromialgia_sinal_do_manto_escala_de_contorno" : 6,
    "sindrome_pos_herpetica_territorio_trigeminal_direito" : 3,
    "sindrome_pos_laminectomia_artrodese_lombar_fixacao_com_parafusos_1" : 3,
    "sindrome_pos_laminectomia_osteoartropatia_facetaria_esquerda_L3_L4_sindrome_facetaria" : 2,
    "tendinopatia_anserina_tendinite_da_pata_de_ganso_direita" : 2,
    "tendinopatia_anserina_tendinite_da_pata_de_ganso_esquerda" : 3,
    "tendinopatia_bicipital_supra_espinal_direita" : 2,
    "tendinopatia_de_aquiles_calcaneo_bilateral" : 2,
    "tendinopatia_de_aquiles_calcaneo_direito" : 2,
    "tendinopatia_de_aquiles_calcaneo_esquerdo" : 4,
    "tendinopatia_supra_espinal_bilateral" : 3,
    "tendinopatia_supra_espinal_direita" : 5,
    "termografia_normal_de_face" : 12,
    "termografia_plantar_normal" : 3,
    "tumor_avancado_de_mama_direita" : 2,
    "tumor_de_mama_esquerda_retracao_de_mamilo_hiper_radiacao" : 3,
    "tumor_de_paratireoide_esquerda" : 2,
    "tumor_maligno_avançado_de_mama_direita" : 2,
    "tumor_maligno_de_mama_direita" : 2,
    "varizes_estase_venosa" : 3,
    "varizes_estase_venosa_modo_fusao" : 2,
    "varizes_estase_venosa_perfurantes_insuficientes_vermelho" : 2
  }
}
